services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - honeypot-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - honeypot-net
    depends_on:
      elasticsearch:
        condition: service_healthy

  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    ports:
      - "2222:2222"  # SSH honeypot
      - "2223:2223"  # Telnet honeypot
    volumes:
      - ./cowrie/etc:/cowrie/cowrie-git/etc
      - cowrie_data:/cowrie/cowrie-git/var
    networks:
      - honeypot-net
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - cowrie_data:/var/log/cowrie:ro
      - filebeat_data:/usr/share/filebeat/data
    networks:
      - honeypot-net
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: filebeat -e -strict.perms=false

volumes:
  es_data:
  cowrie_data:
  filebeat_data:

networks:
  honeypot-net:
    driver: bridge