filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/cowrie/cowrie.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "cowrie-%{+yyyy.MM.dd}"

setup.template.name: "cowrie"
setup.template.pattern: "cowrie-*"
setup.ilm.enabled: false

logging.level: info